spring:
  ai:
    zhipuai:
      api-key: 432156df16b143d0de306258380cba88.MoDsO9pZdQI2MNWh
#    ollama:
#      chat:
#        options:
#          model: qwen3
#      embedding:
#        options:
#          model: qwen3-embedding
#      base-url: http://localhost:11434
    vectorstore:
      enabled: false
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: SpringAiCollection
        initialize-schema: true
    mcp:
      enabled: true
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
        enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  tomcat:
    max-swallow-size: 2MB
    disable-upload-timeout: false

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG